# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'ExchangeRate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExchangeRate
 pod 'SnapKit'
 pod 'Then'
 pod 'RxSwift'
 pod 'RxCocoa'
 pod 'RxKeyboard'
 pod 'ReactorKit'
  target 'ExchangeRateTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Nimble'
  end

  target 'ExchangeRateUITests' do
    # Pods for testing
  end

end
